Update supported versions in the `bin/check-dependencies` script
markshust/docker-magento pull request #1175
Opened 2024-06-20 20:51 UTC by YevhenZvieriev

This PR adds the system requirements of the  2.4.7-p1, 2.4.6-p6, 2.4.5-p8, 2.4.4-p9 versions.

2024-07-09 19:42 UTC, markshust requested changes
I noticed this changeset is very large, even though only 3 new versions were added.

What are your thoughts on re-ordering the `magento_versions` list (and the related `common_dependencies`) so that versions are listed in ascending order? This way, there will be only two lines modified in each future changeset, making it easier to review the updates to this file. Right now, there is a lot of room for human error.

2024-07-27 11:16 UTC, piotrkwiecinski commented on compose/bin/check-dependencies
> +common_dependencies[28]="Composer:2.7 Elasticsearch:8.11 OpenSearch:2.12 MariaDB:10.6 MySQL:8.0 PHP:8.3,8.2 RabbitMQ:3.13 Redis:7.2 Varn``ish:7.5 Apache:2.4 nginx:1.24 'AWS-Aurora-(MySQL)':8.0 'AWS-S
You have a typo `Varn``ish`

2024-07-27 14:25 UTC, piotrkwiecinski approved these changes

2024-07-31 10:32 UTC, markshust approved these changes

2024-07-31 10:33 UTC, merged